[2025-02-16T16:04:25.506+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-16T16:04:25.526+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [queued]>
[2025-02-16T16:04:25.533+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [queued]>
[2025-02-16T16:04:25.534+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-02-16T16:04:25.546+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2025-02-15 12:00:00+00:00
[2025-02-16T16:04:25.552+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1670) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T16:04:25.554+0000] {standard_task_runner.py:63} INFO - Started process 1672 to run task
[2025-02-16T16:04:25.554+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nasa_apod_pipeline', 'create_table', 'scheduled__2025-02-15T12:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/nasa_pipeline_dag.py', '--cfg-path', '/tmp/tmpv3rmz6cl']
[2025-02-16T16:04:25.557+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask create_table
[2025-02-16T16:04:25.602+0000] {task_command.py:426} INFO - Running <TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [running]> on host dfa5576bf540
[2025-02-16T16:04:25.680+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nasa_apod_pipeline' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-15T12:00:00+00:00'
[2025-02-16T16:04:25.682+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-16T16:04:25.695+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS nasa_images (
            id SERIAL PRIMARY KEY,
            date TEXT,
            title TEXT,
            explanation TEXT,
            url TEXT,
            media_type TEXT
        );
        
[2025-02-16T16:04:25.704+0000] {base.py:84} INFO - Using connection ID 'postgres_nasa' for task execution.
[2025-02-16T16:04:25.712+0000] {base.py:84} INFO - Using connection ID 'postgres_nasa' for task execution.
[2025-02-16T16:04:29.453+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-16T16:04:29.454+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "posgres" to address: Name or service not known

[2025-02-16T16:04:29.463+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nasa_apod_pipeline, task_id=create_table, run_id=scheduled__2025-02-15T12:00:00+00:00, execution_date=20250215T120000, start_date=20250216T160425, end_date=20250216T160429
[2025-02-16T16:04:29.475+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task create_table (could not translate host name "posgres" to address: Name or service not known
; 1672)
[2025-02-16T16:04:29.505+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-16T16:04:29.515+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-02-16T16:04:29.527+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T16:04:29.532+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-16T16:08:26.880+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-16T16:08:26.899+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [queued]>
[2025-02-16T16:08:26.909+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [queued]>
[2025-02-16T16:08:26.910+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-02-16T16:08:26.925+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2025-02-15 12:00:00+00:00
[2025-02-16T16:08:26.931+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1741) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T16:08:26.933+0000] {standard_task_runner.py:63} INFO - Started process 1743 to run task
[2025-02-16T16:08:26.933+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nasa_apod_pipeline', 'create_table', 'scheduled__2025-02-15T12:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/nasa_pipeline_dag.py', '--cfg-path', '/tmp/tmpyl8e6jj4']
[2025-02-16T16:08:26.935+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask create_table
[2025-02-16T16:08:26.978+0000] {task_command.py:426} INFO - Running <TaskInstance: nasa_apod_pipeline.create_table scheduled__2025-02-15T12:00:00+00:00 [running]> on host dfa5576bf540
[2025-02-16T16:08:27.050+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nasa_apod_pipeline' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-15T12:00:00+00:00'
[2025-02-16T16:08:27.051+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-16T16:08:27.063+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS nasa_images (
            id SERIAL PRIMARY KEY,
            date TEXT,
            title TEXT,
            explanation TEXT,
            url TEXT,
            media_type TEXT
        );
        
[2025-02-16T16:08:27.070+0000] {base.py:84} INFO - Using connection ID 'postgres_nasa' for task execution.
[2025-02-16T16:08:27.077+0000] {base.py:84} INFO - Using connection ID 'postgres_nasa' for task execution.
[2025-02-16T16:08:30.798+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-16T16:08:30.801+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "posgres" to address: Name or service not known

[2025-02-16T16:08:30.811+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nasa_apod_pipeline, task_id=create_table, run_id=scheduled__2025-02-15T12:00:00+00:00, execution_date=20250215T120000, start_date=20250216T160826, end_date=20250216T160830
[2025-02-16T16:08:30.822+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task create_table (could not translate host name "posgres" to address: Name or service not known
; 1743)
[2025-02-16T16:08:30.847+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-16T16:08:30.857+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-02-16T16:08:30.868+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T16:08:30.873+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
